version: '3.9'

services:
  db:
    image: postgres:15
    container_name: jobs_db
    restart: on-failure
    environment:
      - POSTGRES_DB=jobs
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - jobs_db:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  jobs_db: